export default {
    //基础表单组件源
    base_scource:{
        type: '',
        width: '',
        height: '',
        name: '',
        top: '',
        left: '',
        position: 'absolute',
        isHide: false,
        isDisabled: false,
        index: '',
        isTextBold: false,
        isTextItalics: false,
        isTextUnderLine:false,
        isTextDeleteLine:false,
        fontSize:'14px',
        fontFamily:'',
        padding:'',
        margin:'',
        borderRadius:'',
        color:'',
        isLock:false,
        key:'',
        value:'',
        _key:'',
        _value:'',
        parentName:'',
    },
    //布局容器组件源
    layout_scource:{
        type: '',
        width: '',
        height: '',
        name: '',
        top: '',
        left: '',
        position: 'absolute',
        isHide: false,
        isDisabled: false,
        index: '',
        isBold: false,
        isItalics: false,
        fontSize:'14px',
        fontFamily:'',
        padding:'',
        margin:'',
        borderRadius:'',
        color:'',
        isLock:false,
        key:'',
        value:'',
        _key:'',
        _value:'',
        flex:4,
        children:[]
    },
}