const left_components = [
    {
        name:'基础表单组件',
        type:'base',
        children:[
            {
                name:'按钮',
                type:'l_btn',
                class:'icon-anniu',
                width:'70',
                height:'34',
                handles:[]
            },
            {
                name:'输入框',
                type:'l_input',
                class:'icon-shurukuang',
                width:'200',
                height:'34',
                handles:['tl', 'tm', 'tr', 'mr', 'br', 'bm', 'bl', 'ml']
            },{
                name:'文本框',
                type:'l_textarea',
                class:'icon-wenbenkuang'
            },

            {
                name:'下拉框',
                type:'l_select',
                class:'icon-xialakuangbiaodan'
            },
            {
                name:'单选按钮',
                type:'l_radio',
                class:'icon-danxuananniu'
            },
            {
                name:'开关',
                type:'l_switch',
                class:'icon-kaiguan-guan'
            },
            {
                name:'复选框',
                type:'l_checkbox',
                class:'icon-fuxuankuang'
            },
            {
                name:'日期',
                type:'l_date',
                class:'icon-date'
            },
            {
                name:'上传',
                type:'l_upload',
                class:'icon-upload'
            },
            {
                name:'步骤条',
                type:'l_step',
                class:'icon-step'
            },
            {
                name:'选项卡',
                type:'l_tab',
                class:'icon-xuanxiangqia'
            },
            {
                name:'数字计步器',
                type:'l_n_input',
                class:'icon-shuzishurukuang'
            },
            {
                name:'面包屑导航',
                type:'l_home',
                class:'icon-home'
            },
            {
                name:'分页',
                type:'l_pagination',
                class:'icon-fenye'
            },
            {
                name:'步骤条',
                type:'l_step',
                class:'icon-step'
            },
        ]
    },
    {
        name:'业务组件',
        type:'business',
        children:[
            {
                name:'标题',
                type:'l_title',
                class:'icon-title'
            },
        ]
    },
    {
        name:'形状组件',
        type:'',
        children:[

        ]
    },
];
export default {
    left_components
}
